name: Regions
version: '1.0'
main: lt.mredgariux.regions.main
api-version: '1.20'
depends: ["WorldEdit"]
softdepend:
  - "PlaceholderAPI"
commands:
  rg:
    description: "Regions"
    permission: "regions"
permissions:
  regions.create:
    description: "Create regions"
  regions.list:
    description: "List regions"
  regions.bypass.use.*:
    description: "Bypass any useEvent event cancellations"
  regions.bypass.build.*:
    description: "Bypass any build event cancellations"
  regions.bypass.break.*:
    description: "Bypass any break event cancellations"
  regions.bypass.we.*:
    description: "Bypass worldedit cancellations"